# Generated by chatGPT
# Yet to be tested

from PIL import Image
import base64

# Read the image file
image_path = 'image.jpg'
with open(image_path, 'rb') as f:
    image_data = f.read()

# Encode the image data as base64
base64_encoded_image = base64.b64encode(image_data).decode('utf-8')

# Construct the data URI
mime_type = 'image/jpeg'  # Adjust accordingly for different image formats
data_uri = f'data:{mime_type};base64,{base64_encoded_image}'

print("Data URI:", data_uri)
